// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC70eVuy8ggTbtOSoFy7p5aRWFZ8hFmgU',
    appId: '1:145653103712:web:fe7b17bfde51a063839705',
    messagingSenderId: '145653103712',
    projectId: 'recordapps-e659b',
    authDomain: 'recordapps-e659b.firebaseapp.com',
    storageBucket: 'recordapps-e659b.appspot.com',
    measurementId: 'G-2FG0SMFBPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQDkgVrNofF1ilMnGm4ZZa49wctawwi3E',
    appId: '1:145653103712:android:ca0e88fb95b26652839705',
    messagingSenderId: '145653103712',
    projectId: 'recordapps-e659b',
    storageBucket: 'recordapps-e659b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpIfgG_yXYg3DxD7LvH6VJzeacGoTFBl0',
    appId: '1:145653103712:ios:8f9254b6baae23b9839705',
    messagingSenderId: '145653103712',
    projectId: 'recordapps-e659b',
    storageBucket: 'recordapps-e659b.appspot.com',
    iosBundleId: 'com.example.recordAudioChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpIfgG_yXYg3DxD7LvH6VJzeacGoTFBl0',
    appId: '1:145653103712:ios:8f9254b6baae23b9839705',
    messagingSenderId: '145653103712',
    projectId: 'recordapps-e659b',
    storageBucket: 'recordapps-e659b.appspot.com',
    iosBundleId: 'com.example.recordAudioChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC70eVuy8ggTbtOSoFy7p5aRWFZ8hFmgU',
    appId: '1:145653103712:web:1a1d4d845e505015839705',
    messagingSenderId: '145653103712',
    projectId: 'recordapps-e659b',
    authDomain: 'recordapps-e659b.firebaseapp.com',
    storageBucket: 'recordapps-e659b.appspot.com',
    measurementId: 'G-GD0BQVX6N0',
  );
}
