// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZf9nq74r1KBlyR9YofeyIhqX-U3teRY',
    appId: '1:605279807288:web:48c63569b7911284c543cd',
    messagingSenderId: '605279807288',
    projectId: 'recordapp-aaf3c',
    authDomain: 'recordapp-aaf3c.firebaseapp.com',
    storageBucket: 'recordapp-aaf3c.appspot.com',
    measurementId: 'G-WK7VNTSDNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQow3vTyq3Dh3CU7tXOV92PdOe8INsPE',
    appId: '1:605279807288:android:1df3a59ddcc2f7d6c543cd',
    messagingSenderId: '605279807288',
    projectId: 'recordapp-aaf3c',
    storageBucket: 'recordapp-aaf3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn5J9PpCgfuk4_vNKAb0HVcTm7mNdQv1o',
    appId: '1:605279807288:ios:40256e897c3c90fbc543cd',
    messagingSenderId: '605279807288',
    projectId: 'recordapp-aaf3c',
    storageBucket: 'recordapp-aaf3c.appspot.com',
    iosBundleId: 'com.example.recordAudioChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn5J9PpCgfuk4_vNKAb0HVcTm7mNdQv1o',
    appId: '1:605279807288:ios:40256e897c3c90fbc543cd',
    messagingSenderId: '605279807288',
    projectId: 'recordapp-aaf3c',
    storageBucket: 'recordapp-aaf3c.appspot.com',
    iosBundleId: 'com.example.recordAudioChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHZf9nq74r1KBlyR9YofeyIhqX-U3teRY',
    appId: '1:605279807288:web:3ac09a2ace3d6d45c543cd',
    messagingSenderId: '605279807288',
    projectId: 'recordapp-aaf3c',
    authDomain: 'recordapp-aaf3c.firebaseapp.com',
    storageBucket: 'recordapp-aaf3c.appspot.com',
    measurementId: 'G-TJ0VDMZPEY',
  );
}
